### ISSUE TITLE
xpln: move xpln functions to a separate file from Data.py

### ISSUE THREAD

**Issue by deekay2310** [deekay2310/CSC591-ASE-Project-Group-7#3]
Need to make the codebase more modular with xpln functions in a separate file

**Comment by deekay2310** [comment]
removed xpln function from Data.py @RohanSinha96 in this commit --> [542b568](https://github.com/deekay2310/CSC591-ASE-Project-Group-7/commit/542b5683653606e60bc4a075be905f79e9088229)

you can go ahead and create a separate module for it

**Comment by RohanSinha96** [comment]
Added explain.py to the repo
